### ISSUE TITLE
Decorelate deepgroove from interface.

### ISSUE THREAD

**Issue by fosterrath-mila** [fosterrath-mila/deepgroove_user_exp#1]
I'm trying to debug the interface and I dont have the deepgroove dependencies and it's an impediment. See : 

https://github.com/fosterrath-mila/deepgroove_user_exp/blob/41bfa3278609cee882e8d16b2bb582fe397b6241/deepgroove_web_user_experiment/training_interface.py#L11

Could / should we decorelate with a AbstractBaseClass implemented in a glue module.

**Comment by maximecb** [comment]
You're going to need those dependencies. I sent you an invite to the DeepGroove repo.
